### PR TITLE
Fork repository and pull request

### PR DESCRIPTION
**Pull request by MikelElorza**

### CODE REVIEW

**Comment by MikelElorza** [comment]
I want to start writing the code of the wide field simulations in Julia, so I will start putting some commits here.

**Comment by MikelElorza** [comment]
I think that I don´t understand how can i convert molecules/cm^3 to molecules/cm^2. I would think that this conversion depends on the deposition method.  Furthermore, I would say that it does not make sense in the case of evaporations. Can i put the molecules/micron as the input instead of the molarity of the solution?

**Comment by jjgomezcadenas** [comment]
You are right, this is the particular case in which we start from a chemical solution, but on the other hand, this is what we are going to get from the chemists most of the time, a solution with a given molarity. 

So you can branch the code and consider two possibilities, either input as molarity or as evaporation, in one case you take directly the number of molecules per micron squared in another the molarity. 

To pass from mol/cm^3 to mol/cm^2 the assumption is that you deposit uniformly which is more or less the case for deep coating and spin coating. Notice that it is not really very important. We want to have a rule of thumb to transform molarities into molecules per micron, to do approximate calculations from given molarities (repeat this will be the usual input).

**Comment by MikelElorza** [comment]
Thank you!

Then, to calculate the number of molecules/cm^2 for example in an a x b rectangle I would multiply the infinitesimal volume of the solution on top of the quartz (a x b x dz) by the molecules/cm^3.  I think that i don´t understand what the function toncm2 does. 

I think that I will start using molecules/micron^2 as the input and after I will add the functions to relate this value with the molarity.

**Comment by jjgomezcadenas** [comment]
The hidden assumption is that only one molecule takes the spot in dz (and there is always an available molecule to fill the spot in the solution), so only one infinitesimal layer of molecules (thickness of one molecule) gets deoposited.

**Pull request merged**
